---
slug: developing_in_the_open
filename: developing_in_the_open
title: Developing in the Open
subtitle: One Programmer's Take on Development
description: Change me.
author: Jeremy Friesen
copyright: 2014
uuid: 2698afd7-5ef8-43fa-9017-85728e0dfcde
