---
slug: take_on_rails
filename: take_on_rails
title: Developing in the Open
subtitle: One Programmer's Take on Development
description: Change me.
author: Jeremy Friesen
copyright: 2014
uuid: 2698afd7-5ef8-43fa-9017-85728e0dfcde
