prices:
  -
    code: ebooks
    name: "HTML & Ebook"
    description:
      |
        * Optimized for computer screens, Kindle, and iPad
    media:
      - ebooks
    price: 999
authors:
  -
    name: Jeremy Friesen
    contact_email: jeremy.n.friesen@gmail.com